test -s ~/.alias && . ~/.alias || true

# custom prompt
PS1='\W > '

export TERMINAL="urxvt"

# reminder to use ctrl+l instead of typing "clear"
alias clear='echo Just use ctrl+L && echo'

# see battery percentage with a single command
alias bat='cat /sys/class/power_supply/BAT1/capacity'

# terminal network manager
alias network='nmtui'

# terminal bluetooth manager
alias bt='bluetoothctl'

# copying files to the clipboard from the command line
alias clip='xclip -sel c < '

# reset terminal state - useful when using/making curses based apps
# I always accidentially type "rest" instead of "reset", so I added
# autocorrect
alias rest='reset'

# kill background processes
alias killbg='kill -9 `jobs -ps`'

# get the line count of files
alias len='wc -l'

# curl development alias
alias build-curl='autoreconf -fi && ./configure --with-openssl && make'

alias ff='fastfetch'
alias pico8='~/Apps/PICO8/pico8 &'
alias chocdoom='chocolate-doom -iwad ~/Downloads/doom.wad'
alias nano='nano -Ynone'

alias steam='STEAM_RUNTIME_PREFER_HOST_LIBRARIES=1 steam &'
alias 1password='dbus-run-session nohup flatpak run com.onepassword.OnePassword &'
alias bolt='dbus-run-session nohup flatpak run com.adamcake.Bolt &'

# Created by `pipx` on 2025-07-11 00:31:56
export PATH="$PATH:/home/djaysky/.local/bin"
