test -s ~/.alias && . ~/.alias || true
PS1='\W > '

export TERMINAL="urxvt"

alias network='nmtui'
alias bt='bluetoothctl'
alias rest='reset'
alias killbg='kill -9 `jobs -ps`'
alias len='wc -l'
alias nf='neofetch'
alias pico8='~/Apps/PICO8/pico8 &'

alias steam='STEAM_RUNTIME_PREFER_HOST_LIBRARIES=1 steam'
alias 1password='dbus-run-session nohup flatpak run com.onepassword.OnePassword &'
